FROM node:20 AS frontend_builder

WORKDIR /frontend

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build


FROM node:23-slim AS frontend

RUN npm install -g serve

COPY --from=frontend_builder /frontend/dist /app/dist

EXPOSE 5173

CMD ["serve", "-s", "/app/dist", "-l", "5173"]
