ignore:
  # Go: generated code and stubs
  - "internal/database/gen_models/**"
  - "**/*.gen.go"
  - "internal/**/service_stub.go"

  # Exclude all Go routers from coverage
  - "internal/**/router.go"
  - "**/router.go"

  # Backend-specific exclusions
  - "internal/auth/middleware.go"
  - "internal/database/models/**"

  # Frontend: build outputs, tests, mocks, and configs
  - "frontend/dist/**"
  - "frontend/coverage/**"
  - "frontend/src/__mocks__/**"
  - "frontend/postcss.config.js"
  - "frontend/tailwind.config.js"
  - "frontend/src/App.tsx"       # corrected path
  - "frontend/src/main.tsx"      # corrected path
  # Routes/Types (cover common locations)
  - "frontend/src/routes/**"
  - "frontend/src/types/**"

coverage:
  status:
    project:
      default:
        target: 69%
        threshold: 0%   # allow no drop; raise if you want small fluctuation
      go_unit:
        flags: [go_unit]
        target: 69%
      go_integration:
        flags: [go_integration]
        target: 69%
      frontend:
        flags: [frontend]
        target: 69%
    patch:
      default:
        target: 69%
        threshold: 0%