// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gen_models

const TableNameCompetencyPrerequisite = "competency_prerequisites"

// CompetencyPrerequisite mapped from table <competency_prerequisites>
type CompetencyPrerequisite struct {
	CompetencyID             int32 `gorm:"column:competency_id;primaryKey" json:"competency_id"`
	PrerequisiteCompetencyID int32 `gorm:"column:prerequisite_competency_id;primaryKey" json:"prerequisite_competency_id"`
}

// TableName CompetencyPrerequisite's table name
func (*CompetencyPrerequisite) TableName() string {
	return TableNameCompetencyPrerequisite
}
