// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gen_models

import (
	"time"
)

const TableNameCompetencyDefinition = "competency_definitions"

// CompetencyDefinition mapped from table <competency_definitions>
type CompetencyDefinition struct {
	CompetencyID       int32     `gorm:"column:competency_id;primaryKey;autoIncrement:true" json:"competency_id"`
	CompetencyName     string    `gorm:"column:competency_name;not null" json:"competency_name"`
	Description        string    `gorm:"column:description" json:"description"`
	CompetencyTypeName string    `gorm:"column:competency_type_name" json:"competency_type_name"`
	Source             string    `gorm:"column:source;not null" json:"source"`
	ExpiryPeriodMonths int32     `gorm:"column:expiry_period_months" json:"expiry_period_months"`
	IsActive           bool      `gorm:"column:is_active;not null;default:true" json:"is_active"`
	CreationDate       time.Time `gorm:"column:creation_date;default:CURRENT_TIMESTAMP" json:"creation_date"`
}

// TableName CompetencyDefinition's table name
func (*CompetencyDefinition) TableName() string {
	return TableNameCompetencyDefinition
}
