// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gen_models

import (
	"time"
)

const TableNameCustomEventDefinition = "custom_event_definitions"

// CustomEventDefinition mapped from table <custom_event_definitions>
type CustomEventDefinition struct {
	CustomEventID       int32     `gorm:"column:custom_event_id;primaryKey;autoIncrement:true" json:"custom_event_id"`
	EventName           string    `gorm:"column:event_name;not null" json:"event_name"`
	ActivityDescription string    `gorm:"column:activity_description" json:"activity_description"`
	StandardDuration    string    `gorm:"column:standard_duration" json:"standard_duration"`
	GrantsCertificateID int32     `gorm:"column:grants_certificate_id" json:"grants_certificate_id"`
	Facilitator         string    `gorm:"column:facilitator" json:"facilitator"`
	CreatedBy           string    `gorm:"column:created_by" json:"created_by"`
	CreationDate        time.Time `gorm:"column:creation_date;default:CURRENT_TIMESTAMP" json:"creation_date"`
}

// TableName CustomEventDefinition's table name
func (*CustomEventDefinition) TableName() string {
	return TableNameCustomEventDefinition
}
