// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gen_models

const TableNameCustomEventPrerequisite = "custom_event_prerequisites"

// CustomEventPrerequisite mapped from table <custom_event_prerequisites>
type CustomEventPrerequisite struct {
	EventID             int32 `gorm:"column:event_id;primaryKey" json:"event_id"`
	PrerequisiteEventID int32 `gorm:"column:prerequisite_event_id;primaryKey" json:"prerequisite_event_id"`
}

// TableName CustomEventPrerequisite's table name
func (*CustomEventPrerequisite) TableName() string {
	return TableNameCustomEventPrerequisite
}
