// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gen_models

import (
	"time"
)

const TableNameCustomJobMatrix = "custom_job_matrix"

// CustomJobMatrix mapped from table <custom_job_matrix>
type CustomJobMatrix struct {
	CustomMatrixID     int32     `gorm:"column:custom_matrix_id;primaryKey;autoIncrement:true" json:"custom_matrix_id"`
	EmployeeNumber     string    `gorm:"column:employee_number" json:"employee_number"`
	PositionMatrixCode string    `gorm:"column:position_matrix_code;not null" json:"position_matrix_code"`
	CompetencyID       int32     `gorm:"column:competency_id;not null" json:"competency_id"`
	RequirementStatus  string    `gorm:"column:requirement_status;not null" json:"requirement_status"`
	Notes              string    `gorm:"column:notes" json:"notes"`
	CreatedBy          string    `gorm:"column:created_by" json:"created_by"`
	CreationDate       time.Time `gorm:"column:creation_date;default:CURRENT_TIMESTAMP" json:"creation_date"`
}

// TableName CustomJobMatrix's table name
func (*CustomJobMatrix) TableName() string {
	return TableNameCustomJobMatrix
}
