// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gen_models

import (
	"time"
)

const TableNameCustomEventSchedule = "custom_event_schedules"

// CustomEventSchedule mapped from table <custom_event_schedules>
type CustomEventSchedule struct {
	CustomEventScheduleID int32     `gorm:"column:custom_event_schedule_id;primaryKey;autoIncrement:true" json:"custom_event_schedule_id"`
	CustomEventID         int32     `gorm:"column:custom_event_id;not null" json:"custom_event_id"`
	Title                 string    `gorm:"column:title;not null" json:"title"`
	EventStartDate        time.Time `gorm:"column:event_start_date;not null" json:"event_start_date"`
	EventEndDate          time.Time `gorm:"column:event_end_date;not null" json:"event_end_date"`
	RoomName              string    `gorm:"column:room_name" json:"room_name"`
	MaximumAttendees      int32     `gorm:"column:maximum_attendees" json:"maximum_attendees"`
	MinimumAttendees      int32     `gorm:"column:minimum_attendees" json:"minimum_attendees"`
	StatusName            string    `gorm:"column:status_name;default:Scheduled" json:"status_name"`
	CreationDate          time.Time `gorm:"column:creation_date;default:CURRENT_TIMESTAMP" json:"creation_date"`
}

// TableName CustomEventSchedule's table name
func (*CustomEventSchedule) TableName() string {
	return TableNameCustomEventSchedule
}
