// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gen_models

const TableNameDbRule = "db_rules"

// DbRule mapped from table <db_rules>
type DbRule struct {
	ID      string `gorm:"column:id;primaryKey" json:"id"`
	Enabled bool   `gorm:"column:enabled;not null;default:true" json:"enabled"`
	Type    string `gorm:"column:type;not null" json:"type"`
	Body    string `gorm:"column:body" json:"body"`
}

// TableName DbRule's table name
func (*DbRule) TableName() string {
	return TableNameDbRule
}
