// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gen_models

import (
	"time"
)

const TableNameEmployee = "employee"

// Employee mapped from table <employee>
type Employee struct {
	Employeenumber   string    `gorm:"column:employeenumber;primaryKey" json:"employeenumber"`
	Firstname        string    `gorm:"column:firstname" json:"firstname"`
	Lastname         string    `gorm:"column:lastname" json:"lastname"`
	Useraccountemail string    `gorm:"column:useraccountemail;not null" json:"useraccountemail"`
	Employeestatus   string    `gorm:"column:employeestatus" json:"employeestatus"`
	Terminationdate  time.Time `gorm:"column:terminationdate" json:"terminationdate"`
}

// TableName Employee's table name
func (*Employee) TableName() string {
	return TableNameEmployee
}
