// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gen_models

import (
	"time"
)

const TableNameEvent = "events"

// Event mapped from table <events>
type Event struct {
	ID              int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Title           string    `gorm:"column:title;not null" json:"title"`
	EventType       string    `gorm:"column:event_type" json:"event_type"`
	RelevantParties string    `gorm:"column:relevant_parties" json:"relevant_parties"`
	StartTime       time.Time `gorm:"column:start_time;not null" json:"start_time"`
	EndTime         time.Time `gorm:"column:end_time;not null" json:"end_time"`
	AllDay          bool      `gorm:"column:all_day;not null" json:"all_day"`
}

// TableName Event's table name
func (*Event) TableName() string {
	return TableNameEvent
}
