// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gen_models

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID                 int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Username           string `gorm:"column:username;not null" json:"username"`
	Password           string `gorm:"column:password;not null" json:"password"`
	ForgotPasswordLink string `gorm:"column:forgot_password_link" json:"forgot_password_link"`
	Role               string `gorm:"column:role;default:User" json:"role"`
	EmployeeNumber     string `gorm:"column:employee_number;not null" json:"employee_number"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
