// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package gen_models

const TableNameUserEvent = "user_events"

// UserEvent mapped from table <user_events>
type UserEvent struct {
	ID      int64 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID  int64 `gorm:"column:user_id;not null" json:"user_id"`
	EventID int64 `gorm:"column:event_id;not null" json:"event_id"`
}

// TableName UserEvent's table name
func (*UserEvent) TableName() string {
	return TableNameUserEvent
}
