name: Go-test
on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Build
        run: make build

      - name: GO Integration Tests
        run: make test

      - name: Go Unit Tests
        run: make utest

      - name: Test frontend with Vitest
        run: make ftest

      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v8.0.0
        with:
          only-new-issues: true

      - name: Lint frontend with ESLint
        run: make flint

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage/go-integration.out, ./coverage/go-unit.out, ./frontend/coverage/lcov.info
          flags: go_integration, go_unit, frontend
          fail_ci_if_error: true
          verbose: true

