name: Go-test
on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.x'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: frontend/yarn.lock

      - name: Build
        run: make build
      - name: Test with the Go CLI
        run: make test
      - name: Test frontend with Vitest
        run: make ftest
      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v8.0.0
        with:
          only-new-issues: true

      - name: Lint frontend with ESLint
        run: make flint