name: Go-test
on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.x'

      - name: Build
        run: make build
      - name: Test with the Go CLI
        run: make utest
      - name: Test frontend with Vitest
        run: make ftest
      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v8.0.0
